### ISSUE TITLE
[EPIC] Python support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#256]
Build out Python language support. Initially targeting the support for Ruby that existed in `freshli-lib` (analyzing `requirements.txt` files)

- [ ] Create GitHub repository for `freshli-agent-python`

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-python` to production docker container image
