### ISSUE TITLE
[EPIC] JavaScript support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#257]
Build out JavaScript language support.

This should support both NPM and Yarn dependency manifest formats.

- [ ] Create GitHub repository for `freshli-agent-javascript`

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-javascript` to production docker container image
