### ISSUE TITLE
[EPIC] PHP support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#259]
Build out PHP language support. Initially targeting the support for PHP that existed in `freshli-lib` (analyzing `composer.json` and `composer.lock`).

- [ ] Create GitHub repository for `freshli-agent-php`

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-php` to production docker container image
