### ISSUE TITLE
[EPIC] C# support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#260]
Build out C# language support. Initially targeting the support for C# that existed in `freshli-lib` (analyzing `*.csproj` files).

- [ ] Create GitHub repository for `freshli-agent-csharp`

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-csharp` to production docker container image
