### ISSUE TITLE
[EPIC] Go support

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#261]
Build out Go language support.

- [ ] Create GitHub repository for `freshli-agent-go`

(The following issues should be moved to the repository that's created above once it exists.)
- [ ] Add skeleton command line application
- [ ] Implement `detect-manifest`
- [ ] Implement `process-manifest`
- [ ] Implement `validating-repositories`
- [ ] Implement `retrieve-release-history`
- [ ] Implement `validating-package-urls`
- [ ] Validate against `freshli agents verify` command

(The following issue should belong to this project)
- [ ] Add `freshli-agent-go` to production docker container image
