### ISSUE TITLE
[EPIC] Internal demo of new CLI

### ISSUE THREAD

**Issue by mscottford** [corgibytes/freshli-cli#274]
We're going to demo the `freshli` CLI internally as a step towards being able to schedule a demo with a client. This demo will be very prescriptive; we'll follow a pre-defined set of steps to show off how the application works.

- [x] Write the basic script to follow for the demo (see below)
    - [x] Add acceptance test for analyzing http://github.com/questdb/questdb and make sure it returns a 0 status code (#315)
    - [x] Build production image and push to Docker Hub (#316)
    - [x] Ensure Freshli Web API is deployed (#317)
    - [ ] Fix any bugs that might be found while during a run through of the script (such as when running the analyze command against the QuestDB project) (#318)
- [x] Create images to aid description of the analysis process
- [x] Schedule demo
- [x] Rehearse demo and record timings (how long does it take for the analysis to run?)
- [x] Deliver demo

Demo script:

1. Open a terminal window and run `docker pull corgibytes/freshli-cli:latest`.
2. Run `docker run --rm -it freshli-cli analyze https://github.com/questdb/questdb`
3. Wait for the analysis to finish
4. While the analysis is running, describe how the analysis process works - using images
5. Open the provided URL to view the results
6. Describe each of the graphs that are displayed in the web browser

Linked issues:
- #315
- #316
- #317
- #318

**Comment by mscottford** [comment]
The internal demo was delivered on November 2nd, 2022.
